trigger:
  branches:
    include:
      - master

pool:
  name: 'Default'

variables:
  - group: LoanTrackVariables

stages:
  - stage: Build
    displayName: 'Build Blazor Web App'
    jobs:
      - job: Build
        displayName: 'Build and Publish'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET 9 SDK'
            inputs:
              packageType: 'sdk'
              version: $(dotnetVersion)
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: |
              dotnet restore
              dotnet build --configuration Release --no-restore
            displayName: 'Restore and Build'

          - script: |
              dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
            displayName: 'Publish Blazor Web App'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
              artifactName: 'drop'

  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployBlazorApp
        displayName: 'Deploy to Azure'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(azureWebAppName)
                    package: $(Pipeline.Workspace)/drop
                    runtimeStack: 'DOTNETCORE|9.0'
